#!/usr/bin/env python3
"""Audit the generated skin against params.json, src/param_ids.h and the real Q-Link JSON.

Writes docs/UI_WIRING_AUDIT.md and resources/rc-touch-targets.json. Run tools/skin.sh first.
"""
import importlib.util
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location("skin_design", ROOT / "tools/skin_design.py")
ui = importlib.util.module_from_spec(spec)
spec.loader.exec_module(ui)
params = json.loads((ROOT / "params.json").read_text())
index = {p["key"]: i for i, p in enumerate(params)}
ids = re.findall(r"P_(\w+),", (ROOT / "src/param_ids.h").read_text())
assert ids == list(index), "param_ids.h out of sync with params.json"
siren = (ROOT / "src/siren.cpp").read_text()
dsp = {
    "pitch": "pitchTarget → glide → oscillator / ZAP start", "wave": "selectedWave → band-limited oscillator / noise",
    "rate": "LFO phase increment", "depth": "f = pitch·(1 + depth·LFO)", "lfo_wave": "simd::lfo shape",
    "zap_sweep": "zapEnd = pitch·2^(sweep/12)", "attack": "attackCoeff / ZAP hold", "release": "releaseCoeff",
    "cutoff": "Lowpass::set", "resonance": "Lowpass::set Q (dB)", "delay_time": "EchoConfig.time",
    "feedback": "EchoConfig.feedback", "delay_mix": "EchoConfig.mix → wet gain", "ping": "EchoConfig.ping → pan gains",
    "preset": "Impl::preset snapshot", "output": "outputGain after limiter", "fire": "fireTriggers → pulse / ZAP",
    "latch": "gate", "mode": "SIREN (LFO) / ZAP (sweep)", "stop": "reset, clear LATCH and notes",
}
assert set(dsp) == set(index)
for key in index:
    assert "P_" + key in siren, "no DSP use of " + key
skin = ROOT / "build/skin/Dub Force - VST - Dub Force Siren/Plugin Skins"
tui = json.loads((skin / "TUI.json").read_text())["pageData"]
defs = {d["key"]: d["value"] for d in tui["componentDefinitions"]["localComponentDefinitions"]}
q = json.loads((skin / "Q-Links.json").read_text())
assert q == json.loads((skin / "Q-Links - 8by1.json").read_text())
banks = q["Screen Mode Q-Links"]["map"]
assert len(banks) == 1 and banks[0]["Q-Links"] == q["Program Mode Q-Links"]
active = [i for i in banks[0]["Q-Links"].values() if i >= 0]
assert sorted(active) == list(range(16)), "Q-Links must be exactly parameters 0..15"
popup = len(params)
controls, touch, visible = [], [], set()
for c in defs["SirenPage"]["componentsData"]:
    remap = {m["key"]: m["value"] for m in c["handle remapping"]["map"]}
    if not remap:
        continue
    box = list(map(int, c["bounds"]["bounds"].split()))
    conditional = bool(c["bounds"]["additionalInvalidatingHandles"])
    target = int(remap["Data"].split()[-1])
    if target == popup:
        assert remap.get("Text") == f"Parameter {index['preset']}" or conditional
        target = index["preset"]
    visible.add(target)
    controls.append((c["componentData"]["name"], target, box, conditional))
    if not conditional:
        touch.append(dict(control=c["componentData"]["name"], param=params[target]["key"], bounds=box))
assert visible == set(range(len(params))), sorted(set(range(len(params))) - visible)
# Each knob's control lies in its column and its bank's row.
for i, key in enumerate(ui.QLINKS):
    x, row = ui.column(i % 8), ui.ROWS[i // 8]
    boxes = [b for name, t, b, cond in controls if t == index[key] and not cond]
    assert boxes and all(x <= b[0] and b[0] + b[2] <= x + ui.COL and row <= b[1] and b[1] + b[3] <= row + ui.ROW_H
                         for b in boxes), "control off its knob column: " + key
group = {key: title for _, groups in ui.BANKS for title, keys in groups for key in keys}
rows = []
for i, p in enumerate(params):
    opts = p.get("options")
    span = " / ".join(opts) if opts else f"{p['min']:g}…{p['max']:g} {p.get('unit', '')}".strip()
    default = opts[ui.physical_default(p)] if opts else f"{ui.physical_default(p):g} {p.get('unit', '')}".strip()
    where = f"bank {i // 8 + 1} knob {i % 8 + 1} ({group[p['key']]})" if i < 16 else "touch only"
    rows.append(f"| {i} | `{p['key']}` | {p['name']} | {where} | {dsp[p['key']]} | {span} | {default} |")
text = f"""# UI and Q-Link wiring audit

Generated by `tools/audit_ui.py` from `params.json`, `src/param_ids.h`,
`src/siren.cpp` and the generated native `TUI.json` and Q-Link JSON files.

The single SIREN page mirrors the Force Q-Link banks: the top row is bank 1
(knobs 1–8), the bottom row bank 2 (knobs 9–16), and every knob's control sits in
its own column. Q-Links map exactly parameters 0–15 in knob order through native
slots 13, 9, 5, 1, 14, 10, 6, 2 (bank 1) and 15, 11, 7, 3, 16, 12, 8, 4 (bank 2);
Program Mode uses the same map. Every one of the {len(params)} parameters has a touch
control; only FIRE, LATCH, SIREN/ZAP and STOP are not on a knob. Hidden parameter
{popup} (`preset__open`) only opens the PATCH list and is never saved.

| Index | Key | Name | Q-Link | DSP destination | Range | Default |
| ---: | --- | --- | --- | --- | --- | --- |
""" + "\n".join(rows) + f"""

{len(touch)} unconditional touch regions (bounds in `resources/rc-touch-targets.json`)
were checked for canvas bounds and overlap by `tools/skin_design.py`. Faders are
{ui.COL - 8}×{ui.CONTROL_H} drag areas; WAVE/SHAPE options are {ui.COL - 4} px wide buttons.
Physical touch feel and Q-Link bank selection must be confirmed on the Force.
"""
(ROOT / "docs/UI_WIRING_AUDIT.md").write_text(text)
(ROOT / "resources/rc-touch-targets.json").write_text(json.dumps(touch, indent=2) + "\n")
print(f"UI AUDIT PASS: {len(params)} parameters bound, 16 Q-Links on their knob columns, {len(touch)} touch regions")
