#!/usr/bin/env python3
"""Canonical index-stable parameter descriptor. Regenerate only when schema changes."""
import json
from pathlib import Path
P=[]
def num(key,name,lo,hi,default,unit='',**kw): P.append(dict(key=key,name=name,min=lo,max=hi,default=default,unit=unit,**kw))
def opt(key,name,options,default=0,**kw): P.append(dict(key=key,name=name,options=options.split(','),default=default,**kw))
num('fire','FIRE',0,1,0,momentary=True,hold_ms=250)
opt('latch','LATCH','OFF,ON')
opt('preset','PRESET','Air Raid,Laser,Fog Horn,Police,UFO,Space Echo,Smoke,Clash,Heavy Dub,Deep Orbit,Feedback Madness,Sci-Fi Alarm')
opt('mode','MODE','SIREN,ZAP')
opt('wave','WAVE','SQUARE,SAW,TRIANGLE,SINE,NOISE')
num('pitch','PITCH',60,2400,620,'Hz')
num('level','SIREN LEVEL',0,100,70,'%')
num('noise','NOISE MIX',0,100,0,'%')
opt('lfo_wave','LFO WAVE','TRIANGLE,SQUARE,SAW,SINE')
num('rate','LFO RATE',.05,24,.55,'Hz')
num('depth','LFO DEPTH',0,1400,480,'Hz')
num('attack','ATTACK',.005,1,.01,'s')
num('release','RELEASE',.02,3,.05,'s')
num('lfo2_rate','LFO2 RATE',.03,8,.17,'Hz')
num('lfo2_amount','LFO2 TO RATE',0,100,0,'%')
num('lfo3_rate','LFO3 RATE',.03,8,.11,'Hz')
num('lfo3_amount','LFO3 TO DEPTH',0,100,0,'%')
num('chop_rate','CHOP RATE',.25,32,4,'Hz')
num('chop_amount','CHOP DEPTH',0,100,0,'%')
num('zap_sweep','ZAP SWEEP',-48,48,-24,'st')
num('zap_time','ZAP TIME',.04,1.2,.18,'s')
num('repeat','ZAP REPEAT',0,16,0,'Hz')
opt('filter_type','FILTER','LP,BP,HP')
num('cutoff','CUTOFF',200,9000,4000,'Hz')
num('resonance','RESONANCE',0,20,2,'dB')
num('delay_time','DELAY TIME',.05,3,60/72*.5,'s')
num('feedback','FEEDBACK',0,88,42,'%')
num('delay_mix','ECHO MIX',0,100,100,'%')
num('delay_hp','ECHO HP',40,1200,120,'Hz')
num('delay_lp','ECHO LP',800,12000,7600,'Hz')
num('ping','PING PONG',0,100,0,'%')
opt('character','ECHO TYPE','CLEAN,DESK,SMOKE,ORBIT,CLASH')
num('reverb','REVERB',0,100,16,'%')
num('output','OUTPUT',0,100,100,'%')
for key,name in [('crush','8 BIT'),('invert','INVERT'),('freeze','FREEZE'),('bend','BEND'),('fast','FAST'),('slow','SLOW'),('oct_up','OCT UP'),('oct_down','OCT DOWN'),('kill','KILL'),('filter_hold','FILTER FX')]: opt(key,name,'OFF,ON')
num('stop','STOP',0,1,0,momentary=True)
for group,label in [('osc','OSC'),('master','MASTER')]:
 for band in ['low','mid','high']: num(group+'_'+band,label+' '+band.upper(),-24,12,0,'dB')
Path('params.json').write_text(json.dumps(P,indent=2)+'\n')
Path('src/param_ids.h').write_text('#pragma once\nnamespace dub { enum Param {\n'+''.join('    P_'+p['key']+',\n' for p in P)+'    P_Count\n}; }\n')
if not Path('vst.json').exists(): Path('vst.json').write_text(json.dumps(dict(name='Dub Force Siren',vendor='Dub Force',uid='DbSr',version=1000,so='dub_force_siren.so',params='params.json',layout='layout.conf',build=dict(root='.',sources=['src/engine.cpp','src/siren.cpp','src/effects.cpp'],cflags=['-Isrc','-Ivendor/mpc-vst-plugins/wrapper'],libs=['-lm'])),indent=2)+'\n')
rows=['# Parameters','', 'Indices are persistent VST project-state identifiers. Never reorder existing keys.','', '| Index | Key | Range / options | Default | Units |','|---:|---|---|---|---|']
for i,p in enumerate(P): rows.append(f"| {i} | `{p['key']}` | {', '.join(p['options']) if 'options' in p else str(p['min'])+' .. '+str(p['max'])} | {p['default']} | {p.get('unit','')} |")
rows+=['','All continuous touchscreen mappings are linear in displayed units, as in BARZINE. FIRE is a 250 ms tap trigger (or complete one-shot ZAP); MIDI notes provide press/release and LATCH sustains. Modifier buttons are toggles because native touch release is unconfirmed. STOP clears performance holds, gates and FX tails. Presets are complete native snapshots; character selection recalls its source effect settings.']
Path('docs/PARAMETERS.md').write_text('\n'.join(rows)+'\n')
